#!/usr/bin/env bash
# Installing HAproxy load balancer
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get -y install haproxy=2.6.\*
apt-get -y update

sed -i "/127.0.0.1 localhost/a 52.207.73.219 322850-lb-01\n100.25.165.156 322850-web-01\n100.25.205.35 322850-web-02" /etc/hosts
{
        echo -e "# HAproxy for web servers"
        echo -e "frontend web_frontend"
        echo -e "\tbind *:80"
        echo -e "\tmode http"
        echo -e "\tdefault_backend web_backend"
        echo -e "\nbackend web_backend"
        echo -e "\tbalance roundrobin"
        echo -e "\tserver 322850-web-01 100.25.165.156:80 check"
        echo -e "\tserver 322850-web-02 100.25.205.35:80 check"
} >> /etc/haproxy/haproxy.cfg

echo "ENABLED=1" >> /etc/default/haproxy

service haproxy restart
